# Generated by Django 4.0.10 on 2024-09-25 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='game',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
