# Generated by Django 4.0.10 on 2024-09-25 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='game',
        ),
    ]
